version: '3'
services:
    WayfinderUi:
     image: "wayfinderui:latest"
     links:
      - AuthServer
     depends_on:
      - AuthServer
     ports:
      - "8100:8100"
     environment:
      - IP_ADDR=${IP_ADDR}

    AuthServer:
        image: "authserver:0.0.1"
        ports: 
            - "8080:8080"
        links:
            - mysql1
        depends_on:
            - mysql1

    HighLevelAPI:
        image: "hlapi:0.0.1"
        ports:
            - "8081:8080"
        links:
            - RouteAPI
            - AuthServer
        depends_on:
            - RouteAPI
            - AuthServer

    UserPrefs:
     image: "userprefs:0.0.1"
     links:
       - mysql1
     depends_on:
       - mysql1
     ports:
       - "8083:8080"

    RouteAPI:
      image: "routeapi:0.0.1"
      ports:
        - "8085:8080"
    
    SimulationApi:
      image: "simulationapi:0.0.1"
      ports:
        - "8084:8080"

    EnvironmentApi:
      image: "environmentservice:0.0.1"
      ports:
        - "8086:8080"

    mysql1:
        image: "mysql"
        environment:
            MYSQL_USER: james
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: wayfinder
            MYSQL_ROOT_PASSWORD: wayfinders
        container_name: mysql1
