/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;


import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import ie.tcd.wayfinder.simulation.Startup;
import ie.tcd.wayfinders.restLibrary.Library;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = Startup.class)
@AutoConfigureMockMvc(secure = true)

public class LibraryTest {
    
    @Autowired
    private MockMvc mvc;
    @Test
    public void getSimulation() throws Exception {
        mvc.perform(MockMvcRequestBuilders.get("/getSimulation/")
                .contentType(MediaType.APPLICATION_JSON)
                .accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk());
    }

    
    
}
