/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.Mockito;

import static org.junit.Assert.*;
import static org.mockito.ArgumentMatchers.*;

import java.io.BufferedReader;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test
    public void get_200OK_noProperties() {
        String url = "test.com";
        
        try
        {
            HttpURLConnection huc = Mockito.mock(HttpURLConnection.class);
            URL u = Mockito.mock(URL.class);
            BufferedReader bufferedReader = Mockito.mock(BufferedReader.class);
            
            
            
            Mockito.when(huc.getResponseCode()).thenReturn(200);
            Mockito.when(bufferedReader.readLine()).thenReturn("OK");
            Mockito.when(u.openConnection()).thenReturn(huc);
            
            String response = Library.GET(url,  null);
            
            assertEquals(response, "OK");
            
        } catch (IOException e)
        {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
    }
    /*
     * 200 OK
     * 200 OK Fail  
     * 
     * 202 Accepted 
     * 
     * 204 No Content
     * 204 No Content fail
     * 
     * 500 
     * 
     * 400 
     * 
     * 404
     *
     * 
     * 
     * 
     * 
     */
    
    
}
